version: "2"

volumes:
  data:

services:

  test_unit:
    image: gcr.io/overleaf-ops/node:10.19.0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      MOCHA_GREP: ${MOCHA_GREP}
    command: npm run test:unit:app
    user: node

  test_acceptance:
    image: gcr.io/overleaf-ops/node:10.19.0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      REDIS_HOST: redis
      MONGO_URL: "mongodb://mongo/sharelatex"
      SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
      PROJECT_HISTORY_ENABLED: 'true'
      LINKED_URL_PROXY: 'http://localhost:6543'
      ENABLED_LINKED_FILE_TYPES: 'url,project_file,project_output_file,mendeley,zotero'
      MOCHA_GREP: ${MOCHA_GREP}
      NODE_ENV: test
      SHARELATEX_CONFIG:
    command: npm run test:acceptance:app
    depends_on:
      - redis
      - mongo
    command: npm run test:acceptance:app

  test_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:frontend:single

  redis:
    image: redis

  mongo:
    image: mongo:3.6.16
